# This is a config for E2B sandbox template.
# You can use template ID (3c626no0oswu49azse48) or template name (latest-nextjs-app) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("latest-nextjs-app") # Sync sandbox
# sandbox = await AsyncSandbox.create("latest-nextjs-app") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('latest-nextjs-app')

team_id = "099f5729-aa16-4a84-aa50-852c6ce6fd0a"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "latest-nextjs-app"
template_id = "3c626no0oswu49azse48"
